note_app/note_app/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  resources :projects do
    member do
      put 'complete'
    end
    member do
      put 'reverse_status'
    end
    resources :tasks do
      member do
        put 'complete'
      end
      member do
        put 'reverse_status'
    end
    end
  end

  root 'projects#index'

#                   Prefix Verb   URI Pattern                                        Controller#Action
#         new_user_session GET    /users/sign_in(.:format)                           devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                           devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                          devise/sessions#destroy
#            user_password POST   /users/password(.:format)                          devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)                      devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)                     devise/passwords#edit
#                          PATCH  /users/password(.:format)                          devise/passwords#update
#                          PUT    /users/password(.:format)                          devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                            registrations#cancel
#        user_registration POST   /users(.:format)                                   registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                           registrations#new
#   edit_user_registration GET    /users/edit(.:format)                              registrations#edit
#                          PATCH  /users(.:format)                                   registrations#update
#                          PUT    /users(.:format)                                   registrations#update
#                          DELETE /users(.:format)                                   registrations#destroy
#                    users GET    /users(.:format)                                   users#index
#                          POST   /users(.:format)                                   users#create
#                 new_user GET    /users/new(.:format)                               users#new
#                edit_user GET    /users/:id/edit(.:format)                          users#edit
#                     user GET    /users/:id(.:format)                               users#show
#                          PATCH  /users/:id(.:format)                               users#update
#                          PUT    /users/:id(.:format)                               users#update
#                          DELETE /users/:id(.:format)                               users#destroy
#         complete_project PUT    /projects/:id/complete(.:format)                   projects#complete
#    complete_project_task PUT    /projects/:project_id/tasks/:id/complete(.:format) tasks#complete
#            project_tasks GET    /projects/:project_id/tasks(.:format)              tasks#index
#                          POST   /projects/:project_id/tasks(.:format)              tasks#create
#         new_project_task GET    /projects/:project_id/tasks/new(.:format)          tasks#new
#        edit_project_task GET    /projects/:project_id/tasks/:id/edit(.:format)     tasks#edit
#             project_task GET    /projects/:project_id/tasks/:id(.:format)          tasks#show
#                          PATCH  /projects/:project_id/tasks/:id(.:format)          tasks#update
#                          PUT    /projects/:project_id/tasks/:id(.:format)          tasks#update
#                          DELETE /projects/:project_id/tasks/:id(.:format)          tasks#destroy
#                 projects GET    /projects(.:format)                                projects#index
#                          POST   /projects(.:format)                                projects#create
#              new_project GET    /projects/new(.:format)                            projects#new
#             edit_project GET    /projects/:id/edit(.:format)                       projects#edit
#                  project GET    /projects/:id(.:format)                            projects#show
#                          PATCH  /projects/:id(.:format)                            projects#update
#                          PUT    /projects/:id(.:format)                            projects#update
#                          DELETE /projects/:id(.:format)                            projects#destroy
#                     root GET    /                                                  projects#index

end

note_app/note_app/app/models/project.rb
class Project < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_many :tasks
end

note_app/note_app/app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :projects
	belongs_to :users
end

note_app/note_app/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :projects
  has_many :tasks
end

note_app/note_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

note_app/note_app/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	skip_before_action :verify_authenticity_token

	def index
		@user =  current_user

	end

	def show

		@project = Project.find(params[:id])

	end


	def new
 		@project = Project.new
	end

	def create
    @project = Project.create(project_params)
    # binding.pry
    @project.users << current_user
    redirect_to '/'
	end

	def edit
		@project = Project.find(params[:id])
	end

	def update
		@project = Project.find(params[:id])
    @project.update_attributes(project_params)
    redirect_to project_path(@project.id)
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to projects_path
	end

	# def add_user
	# 	project = Project.find(params[:id])
	# 	newuser_email = User.where('user_name' )

	# end

	def complete

		project = Project.find(params[:id])


    project.update_attribute(:status, true)
    

    redirect_to root_path

	end

		def reverse_status
		project = Project.find(params[:id])

    project.update_attribute(:status, false)

    redirect_to root_path

	end



	private

	def project_params
    params.require(:project).permit(:name, :description, :status)
  end

end

note_app/note_app/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:fname, :lname, :user_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:fname, :lname, :user_name, :email, :password, :password_confirmation, :current_password)
  end
end

note_app/note_app/app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	skip_before_action :verify_authenticity_token
	
	def new

 		@task = Task.new

		@project = Project.find(params[:project_id])

	end


	def create

		@task = Task.new(task_params)
		@task.project_id = params[:project_id]

		# binding.pry 

		if @task.save
			redirect_to project_path(@task.project_id)
		else
			render :new
		end
	end

	def edit
		@project = Project.find(params[:project_id])
		@task = Task.find(params[:id])
	end


	def update

		@task = Task.find(params[:id])
    @task.update_attributes(task_params)
    redirect_to project_path(@task.project_id)

	end


	def destroy
		@task = Task.find(params[:id])
		@task.destroy
		redirect_to project_path(@task.project_id)
	end
	


	def complete
		task = Task.find(params[:id])


    task.update_attribute(:status, true)
    

    redirect_to project_path(task.project_id)

	end

	def reverse_status
		task = Task.find(params[:id])

    task.update_attribute(:status, false)

    redirect_to project_path(task.project_id)

	end



	private

	def task_params
    params.require(:task).permit(:name, :description, :status)
  end

end

note_app/note_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

	

end

note_app/note_app/app/helpers/application_helper.rb
module ApplicationHelper
end

note_app/note_app/app/helpers/projects_helper.rb
module ProjectsHelper
end

note_app/note_app/app/helpers/tasks_helper.rb
module TasksHelper
end

note_app/note_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DidIt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>


<div id="title">
  <div class="container">
    <h1 id="title-text">DIDIT</h1>
  </div>
</div>

<div class="container">


<%= yield %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>



<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

</div>

</body>
</html>

note_app/note_app/app/views/projects/edit.html.erb
<h3>Edit Project</h3>


<form action="/projects/<%=@project.id%>/" method="post">
	<input type="hidden" name="_method" value="put">
	<label>Name: </label>
	<input type="text" name="project[name]" value="<%=@project.name%>"></br>
	<label>Description: </label>
	<input type="text" name="project[description]" value="<%=@project.description%>"></br>


	<input type="submit" value="Submit">

</form><br>

<p><%= link_to "Delete Project", project_path(@project), :method=>:delete %></p>

<p><%= link_to "Back", projects_path%></p>

note_app/note_app/app/views/projects/index.html.erb
<h5>Hi <%=@user.fname %>! Let's do some work!</h5>


<%= link_to "Create New Project", new_project_path %>

<h3>Active Projects</h3>

<table>
	<thread>
		<tr>
			<th> </th>
			<th>Project Name</th>
			<th>Description</th>
			<th> </th>
		</tr>
	</thread>
	<tbody>
<% @user.projects.where(status: false).each do |proj| %>
	<tr>
		<td><%= button_to "DidIt", complete_project_path(proj), method: :put, :class => "button-primary lower-pad" %></td>
		<td><%= proj.name %></td>
		<td><%= proj.description %></td>
		<td><%= link_to "View", project_path(proj.id) %></td>
		
	
	</tr>
	</tbody>
<%end%>
</table>


<h3>Completed Projects</h3>
<table>
<% @user.projects.where(status: true).each do |proj| %>
	<tr>
		<td><%= button_to "ReDo", reverse_status_project_path(proj), method: :put %></td>
	<td><%= proj.name %></td>
	<td><%= link_to "View", project_path(proj.id) %></td>
	
	
	</tr>
<%end%>
</table>

note_app/note_app/app/views/projects/new.html.erb
<h3>Make a new project!</h3>

<%= form_for @project do |form| %>
  Name:</br> <%= form.text_field :name %></br>
  Description:</br> <%= form.text_field :description %></br>
  <%= form.submit %>
<% end %>

<p><%= link_to "Back", projects_path%></p>

note_app/note_app/app/views/projects/show.html.erb
<h1><%= @project.name%></h1>

<p><%= link_to "Edit Project", edit_project_path(@project.id) %></p>


<%= link_to "Add A New Task", new_project_task_path(@project.id) %>




<h3>Active Tasks</h3>

<table>
	<thread>
		<tr>
			<th> </th>
			<th>Task Name</th>
			<th>Note</th>
			<th> </th>
		</tr>
	</thread>
	<tbody>
	<% @project.tasks.where(status: false).each do |task|%>
	<tr>
		<td><%= button_to "DidIt", complete_project_task_path(@project,task), method: :put, class: "button-primary" %></td>
		<td><%=task.name%></td>
		<td><%=task.description%></td>
		<td><%= link_to "Edit", edit_project_task_path(@project,task) %></td>
	</tr>
	</tbody>
<%end%>
</table>





<h3>Completed Tasks</h3>
<table>
<% @project.tasks.where(status: true).each do |task|%>
	<tr>
		<td><%= button_to "ReDo", reverse_status_project_task_path(@project,task), method: :put %></td>
		<td><%=task.name%></td>
		

	</tr>
<%end%>

</table>

<p><%= link_to "Back", projects_path%></p>

note_app/note_app/app/views/tasks/edit.html.erb
<h3>Edit Task</h3>


<form action="/projects/<%=@project.id%>/tasks/<%=@task.id%>" method="post">
	<input type="hidden" name="_method" value="put">
	<label>Name: </label>
	<input type="text" name="task[name]" value="<%=@task.name%>"></br>
	<label>Note: </label>
	<input type="text" name="task[description]" value="<%=@task.description%>"></br>


	<input type="submit" value="Submit">

</form><br>

<p><%= link_to "Delete Task", project_task_path(@project, @task), :method=>:delete %></p>

<p><%= link_to "Back", project_path(@project)%></p>

note_app/note_app/app/views/tasks/new.html.erb
<h3>Create a New Task!</h3>

<form action="/projects/<%=@project.id%>/tasks" method="post">
	<label>Name: </label>
	<input type="text" name="task[name]"></br>
	<label>Note: </label>
	<input type="text" name="task[description]" ></br>


	<input type="submit" value="Submit">
</form>

<p><%= link_to "Back", project_path(@project)%></p>